name: Clojure CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '21'
        java-package: jdk
        architecture: x64
    - name: Install dependencies
      run: lein sub install
    - name: Run tests
      run: lein sub test
